version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ruby-pdf-practice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - ./api:/usr/src/app:delegated
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true
    stdin_open: true
